/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForPatientsRouteImport } from './routes/for-patients'
import { Route as ForProvidersRouteImport } from './routes/for-providers'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OurServicesRouteImport } from './routes/our-services'
import { Route as RadiologistsRouteImport } from './routes/radiologists'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as OurServicesIndexRouteImport } from './routes/our-services.index'
import { Route as OurServicesSlugRouteImport } from './routes/our-services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPatientsRoute = ForPatientsRouteImport.update({
  id: '/for-patients',
  path: '/for-patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProvidersRoute = ForProvidersRouteImport.update({
  id: '/for-providers',
  path: '/for-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OurServicesRoute = OurServicesRouteImport.update({
  id: '/our-services',
  path: '/our-services',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiologistsRoute = RadiologistsRouteImport.update({
  id: '/radiologists',
  path: '/radiologists',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocationsRoute,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocationsRoute,
} as any)
const OurServicesIndexRoute = OurServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OurServicesRoute,
} as any)
const OurServicesSlugRoute = OurServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OurServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-patients': typeof ForPatientsRoute
  '/for-providers': typeof ForProvidersRoute
  '/locations': typeof LocationsRouteWithChildren
  '/news': typeof NewsRoute
  '/our-services': typeof OurServicesRouteWithChildren
  '/radiologists': typeof RadiologistsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/our-services/$slug': typeof OurServicesSlugRoute
  '/locations/': typeof LocationsIndexRoute
  '/our-services/': typeof OurServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-patients': typeof ForPatientsRoute
  '/for-providers': typeof ForProvidersRoute
  '/news': typeof NewsRoute
  '/radiologists': typeof RadiologistsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/our-services/$slug': typeof OurServicesSlugRoute
  '/locations': typeof LocationsIndexRoute
  '/our-services': typeof OurServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-patients': typeof ForPatientsRoute
  '/for-providers': typeof ForProvidersRoute
  '/locations': typeof LocationsRouteWithChildren
  '/news': typeof NewsRoute
  '/our-services': typeof OurServicesRouteWithChildren
  '/radiologists': typeof RadiologistsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/our-services/$slug': typeof OurServicesSlugRoute
  '/locations/': typeof LocationsIndexRoute
  '/our-services/': typeof OurServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/for-patients'
    | '/for-providers'
    | '/locations'
    | '/news'
    | '/our-services'
    | '/radiologists'
    | '/locations/$slug'
    | '/our-services/$slug'
    | '/locations/'
    | '/our-services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/for-patients'
    | '/for-providers'
    | '/news'
    | '/radiologists'
    | '/locations/$slug'
    | '/our-services/$slug'
    | '/locations'
    | '/our-services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/for-patients'
    | '/for-providers'
    | '/locations'
    | '/news'
    | '/our-services'
    | '/radiologists'
    | '/locations/$slug'
    | '/our-services/$slug'
    | '/locations/'
    | '/our-services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForPatientsRoute: typeof ForPatientsRoute
  ForProvidersRoute: typeof ForProvidersRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  NewsRoute: typeof NewsRoute
  OurServicesRoute: typeof OurServicesRouteWithChildren
  RadiologistsRoute: typeof RadiologistsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-patients': {
      id: '/for-patients'
      path: '/for-patients'
      fullPath: '/for-patients'
      preLoaderRoute: typeof ForPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-providers': {
      id: '/for-providers'
      path: '/for-providers'
      fullPath: '/for-providers'
      preLoaderRoute: typeof ForProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-services': {
      id: '/our-services'
      path: '/our-services'
      fullPath: '/our-services'
      preLoaderRoute: typeof OurServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radiologists': {
      id: '/radiologists'
      path: '/radiologists'
      fullPath: '/radiologists'
      preLoaderRoute: typeof RadiologistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/our-services/': {
      id: '/our-services/'
      path: '/'
      fullPath: '/our-services/'
      preLoaderRoute: typeof OurServicesIndexRouteImport
      parentRoute: typeof OurServicesRoute
    }
    '/our-services/$slug': {
      id: '/our-services/$slug'
      path: '/$slug'
      fullPath: '/our-services/$slug'
      preLoaderRoute: typeof OurServicesSlugRouteImport
      parentRoute: typeof OurServicesRoute
    }
  }
}

interface LocationsRouteChildren {
  LocationsSlugRoute: typeof LocationsSlugRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsSlugRoute: LocationsSlugRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

interface OurServicesRouteChildren {
  OurServicesSlugRoute: typeof OurServicesSlugRoute
  OurServicesIndexRoute: typeof OurServicesIndexRoute
}

const OurServicesRouteChildren: OurServicesRouteChildren = {
  OurServicesSlugRoute: OurServicesSlugRoute,
  OurServicesIndexRoute: OurServicesIndexRoute,
}

const OurServicesRouteWithChildren = OurServicesRoute._addFileChildren(
  OurServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForPatientsRoute: ForPatientsRoute,
  ForProvidersRoute: ForProvidersRoute,
  LocationsRoute: LocationsRouteWithChildren,
  NewsRoute: NewsRoute,
  OurServicesRoute: OurServicesRouteWithChildren,
  RadiologistsRoute: RadiologistsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
